version: '3.8'

services:
  myserver:
    build:
      context: ./server
    container_name: myserver
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_PORT=80
    volumes:
      - ./server:/app
      - /app/node_modules

  myclient:
    build:
      context: ./attack
    container_name: myclient
    environment:
      - SERVER_PORT=80
      - SERVER_IP=myserver
    volumes:
      - ./attack:/app
      - /app/node_modules
    depends_on:
      - myserver

  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
    - '8080:8080'
