version: '3.8'

services:
  nginx:
    image: nginx:1.16.0
    container_name: myserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server/keys/certificate.crt:/etc/nginx/ssl/certificate.crt:ro
      - ./server/keys/certificate.key:/etc/nginx/ssl/certificate.key:ro
      - ./server/nginx.conf:/etc/nginx/nginx.conf:ro
  cadvisor:
    image: 'google/cadvisor:latest'
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk:/dev/disk/:ro
    ports:
    - '8080:8080'
